services:
  user_db:
    image: postgres
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_USER_DATABASE
    ports:
      - 3101:$DB_PORT
    volumes:
      - udb:/var/lib/postgresql/data

  app_user:
    depends_on:
      - user_db
    build: ./app_user
    env_file:
      - ./.env
    ports:
      - 3001:$USER_PORT
    environment:
      - DB_HOST=user_db
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_DATABASE=$DB_USER_DATABASE
      - DB_PORT=$DB_PORT
      - JWT_SECRET=$JWT_SECRET
      - JWT_ENC_ALGO=$JWT_ENC_ALGO
      - JWT_EXPIRY=$JWT_EXPIRY
      - HASH_ALGO=$HASH_ALGO
      - BACKEND_PORT=$USER_PORT
      - AMQP_HOST=$AMQP_HOST
      - AMQP_PASS=$AMQP_PASS
    deploy:
      mode: replicated
      replicas: 1

  device_db:
    image: postgres
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_DEVICE_DATABASE
    ports:
      - 3102:$DB_PORT
    volumes:
      - ddb:/var/lib/postgresql/data

  app_device:
    depends_on:
      - app_user
      - device_db
    build: ./app_device
    env_file:
      - ./.env
    ports:
      - 3002:$DEVICE_PORT
    environment:
      - DB_HOST=device_db
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_DATABASE=$DB_DEVICE_DATABASE
      - DB_PORT=$DB_PORT
      - JWT_SECRET=$JWT_SECRET
      - JWT_ENC_ALGO=$JWT_ENC_ALGO
      - JWT_EXPIRY=$JWT_EXPIRY
      - HASH_ALGO=$HASH_ALGO
      - BACKEND_PORT=$DEVICE_PORT
      - AMQP_HOST=$AMQP_HOST
      - AMQP_PASS=$AMQP_PASS
    deploy:
      mode: replicated
      replicas: 1

  monitor_db:
    image: postgres
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_MONITOR_DATABASE
    ports:
      - 3103:$DB_PORT
    volumes:
      - mdb:/var/lib/postgresql/data

  app_monitor:
    depends_on:
      - app_user
      - app_device
      - monitor_db
    build: ./app_monitor
    env_file:
      - ./.env
    ports:
      - 3003:$MONITOR_PORT
      - 4000:$WEBSOCKET1_PORT
    environment:
      - DB_HOST=monitor_db
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_DATABASE=$DB_MONITOR_DATABASE
      - DB_PORT=$DB_PORT
      - JWT_SECRET=$JWT_SECRET
      - JWT_ENC_ALGO=$JWT_ENC_ALGO
      - JWT_EXPIRY=$JWT_EXPIRY
      - HASH_ALGO=$HASH_ALGO
      - BACKEND_PORT=$MONITOR_PORT
      - WEBSOCKET_PORT=$WEBSOCKET1_PORT
      - AMQP_HOST=$AMQP_HOST
      - AMQP_PASS=$AMQP_PASS

  app_frontend:
    depends_on:
      - app_user
      - app_device
      - app_monitor
    build: ./app_frontend
    env_file:
      - ./.env
    ports:
      - 5000:$FRONTEND_PORT
    environment:
      - VITE_USER_URL=$VITE_USER_URL
      - VITE_DEVICE_URL=$VITE_DEVICE_URL
      - VITE_MONITOR_URL=$VITE_MONITOR_URL
      - VITE_WEBSOCKET1_HOST=$WEBSOCKET1_HOST
      - VITE_WEBSOCKET1_PORT=$WEBSOCKET1_PORT

  caddy:
    image: caddy
    container_name: caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app_user
      - app_device
      - app_monitor
      - app_frontend

volumes:
  udb:
  ddb:
  mdb:
  caddy_data:
  caddy_config: